#pragma once

#include "osgx/Core.hpp"
#include "osgx/Visitors.hpp"
#include "osgx/Array.hpp"
#include "osgx/Callbacks.hpp"
#include "osgx/Picking.hpp"
#include "osgx/Manipulators.hpp"
#include "osgx/Grid.hpp"
#include "osgx/Shader.hpp"
#include "osgx/PBR.hpp"
#include "osgx/IBL.hpp"
#include "osgx/CaptureCubeMap.hpp"
#include "osgx/GGXPrefilter.hpp"
#include "osgx/LambertianBake.hpp"
